name: deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - name: ssh key generate
        run: |
          echo "$DEPLOY_KEY_SERVER" > key
          chmod 600 key
        env:
          DEPLOY_KEY_SERVER: ${{ secrets.DEPLOY_KEY_SERVER }}

      # - name: ssh
      #   run: ssh -i key -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no "${DEPLOY_USER_SERVER}@${DEPLOY_HOST_SERVER}"
      #   env:
      #     DEPLOY_USER_SERVER: ${{ secrets.DEPLOY_USER_SERVER }}
      #     DEPLOY_HOST_SERVER: ${{ secrets.DEPLOY_HOST_SERVER }}

      # 同期のための rsync コマンド。後ほど詳述
      - name: rsync deploy
        run: rsync --checksum -av --delete -e "ssh -i key -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no" ./a/* "${DEPLOY_USER_SERVER}@${DEPLOY_HOST_SERVER}:/opt/csv_deploy/"
        env:
          DEPLOY_USER_SERVER: ${{ secrets.DEPLOY_USER_SERVER }}
          DEPLOY_HOST_SERVER: ${{ secrets.DEPLOY_HOST_SERVER }}
